cc_library(
    name = "my_xla",
    deps = [
        "@xla//xla:array4d",
        "@xla//xla:literal",
        "@xla//xla:statusor",
        "@xla//xla:types",
        "@xla//xla:xla_data_proto_cc",
        "@xla//xla/client",
        "@xla//xla/client:client_library",
        "@xla//xla/client:global_data",
        "@xla//xla/client:local_client",
        "@xla//xla/client:xla_builder",
        "@xla//xla/client:xla_computation",
        "@com_google_absl//absl/strings:str_format",
        "@tsl//tsl/platform:logging",
        "@tsl//tsl/platform:platform_port",
    ],
    alwayslink = True,
)
