on:
  workflow_dispatch:
  push:
    branches:
      - linux-cpu-static
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
    - name: Get today's date
      run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - name: Create release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TODAY }}
        release_name: XLA nightly ${{ env.TODAY }}
        body: "XLA nightly ${{ env.TODAY }}"
  linux-cpu-static:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build XLA static Linux CPU
      run: |
        git clone https://github.com/openxla/xla
        # horrible hack, just to get something working
        rm xla/xla/BUILD
        mv BUILD xla/xla
        cd xla
        docker run --name xla -w /xla -it -d --rm -v $PWD:/xla tensorflow/build:latest-python3.9 bash
        docker exec xla ./configure.py --backend=CPU
        docker exec xla bazel build --test_output=all --spawn_strategy=sandboxed //xla:name_me
    - name: Publish build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: everything.tar.gz
        asset_name: everything.tar.gz
        asset_content_type: application/gzip
